### PR TITLE
Adding feed to docker tag on trevorsullivan.net

### PR DESCRIPTION
**Pull request by pcgeek86**
Adding feed to docker tag on trevorsullivan.net

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
gotta solve those merge conflicts man

**Comment by gianarb** [comment]
it's pretty easy :) thanks

**Comment by gianarb** [comment]
The main problem is that you are not putting in a RSS/atom feed.. :)

**Comment by gianarb** [comment]
Probably this is the correct one
https://trevorsullivan.net/tag/docker/feed/ can you check please?

**Comment by gianarb** [comment]
Added thanks!

**Pull request closed without merging**
